pipeline {
    agent any

    environment {
        BACKEND_IMAGE = 'tranminh2014.tm@gmail.com/docker-backend'
        FRONTEND_IMAGE = 'tranminh2014.tm@gmail.com/docker-frontend '
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/quakhubuon/User-Management.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'docker build -t ${BACKEND_IMAGE} .'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'docker build -t ${FRONTEND_IMAGE} .'
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD')]) {
                    sh 'docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}'
                    sh 'docker tag ${BACKEND_IMAGE} ${DOCKER_HUB_USER}/${BACKEND_IMAGE}:latest'
                    sh 'docker tag ${FRONTEND_IMAGE} ${DOCKER_HUB_USER}/${FRONTEND_IMAGE}:latest'
                    sh 'docker push ${DOCKER_HUB_USER}/${BACKEND_IMAGE}:latest'
                    sh 'docker push ${DOCKER_HUB_USER}/${FRONTEND_IMAGE}:latest'
                }
            }
        }

        stage('Run Docker Compose') {
            steps {
                sh 'docker-compose down && docker-compose up -d'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}